//
// DO NOT EDIT.
//
// Generated by the protocol buffer compiler.
// Source: pb/app_control/app_control.proto
//

//
// Copyright 2018, gRPC Authors All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import GRPC
import NIO
import NIOConcurrencyHelpers
import SwiftProtobuf


/// Usage: instantiate `AppControl_AppControlClient`, then call methods of this protocol to make API calls.
internal protocol AppControl_AppControlClientProtocol: GRPCClient {
  var serviceName: String { get }
  var interceptors: AppControl_AppControlClientInterceptorFactoryProtocol? { get }

  func changeMicrophoneStatus(
    _ request: AppControl_ChangeMicrophoneStatusRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<AppControl_ChangeMicrophoneStatusRequest, SwiftProtobuf.Google_Protobuf_Empty>
}

extension AppControl_AppControlClientProtocol {
  internal var serviceName: String {
    return "app_control.AppControl"
  }

  /// Unary call to ChangeMicrophoneStatus
  ///
  /// - Parameters:
  ///   - request: Request to send to ChangeMicrophoneStatus.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func changeMicrophoneStatus(
    _ request: AppControl_ChangeMicrophoneStatusRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<AppControl_ChangeMicrophoneStatusRequest, SwiftProtobuf.Google_Protobuf_Empty> {
    return self.makeUnaryCall(
      path: AppControl_AppControlClientMetadata.Methods.changeMicrophoneStatus.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeChangeMicrophoneStatusInterceptors() ?? []
    )
  }
}

#if compiler(>=5.6)
@available(*, deprecated)
extension AppControl_AppControlClient: @unchecked Sendable {}
#endif // compiler(>=5.6)

@available(*, deprecated, renamed: "AppControl_AppControlNIOClient")
internal final class AppControl_AppControlClient: AppControl_AppControlClientProtocol {
  private let lock = Lock()
  private var _defaultCallOptions: CallOptions
  private var _interceptors: AppControl_AppControlClientInterceptorFactoryProtocol?
  internal let channel: GRPCChannel
  internal var defaultCallOptions: CallOptions {
    get { self.lock.withLock { return self._defaultCallOptions } }
    set { self.lock.withLockVoid { self._defaultCallOptions = newValue } }
  }
  internal var interceptors: AppControl_AppControlClientInterceptorFactoryProtocol? {
    get { self.lock.withLock { return self._interceptors } }
    set { self.lock.withLockVoid { self._interceptors = newValue } }
  }

  /// Creates a client for the app_control.AppControl service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  internal init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: AppControl_AppControlClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self._defaultCallOptions = defaultCallOptions
    self._interceptors = interceptors
  }
}

internal struct AppControl_AppControlNIOClient: AppControl_AppControlClientProtocol {
  internal var channel: GRPCChannel
  internal var defaultCallOptions: CallOptions
  internal var interceptors: AppControl_AppControlClientInterceptorFactoryProtocol?

  /// Creates a client for the app_control.AppControl service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  internal init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: AppControl_AppControlClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

#if compiler(>=5.6)
@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
internal protocol AppControl_AppControlAsyncClientProtocol: GRPCClient {
  static var serviceDescriptor: GRPCServiceDescriptor { get }
  var interceptors: AppControl_AppControlClientInterceptorFactoryProtocol? { get }

  func makeChangeMicrophoneStatusCall(
    _ request: AppControl_ChangeMicrophoneStatusRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<AppControl_ChangeMicrophoneStatusRequest, SwiftProtobuf.Google_Protobuf_Empty>
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension AppControl_AppControlAsyncClientProtocol {
  internal static var serviceDescriptor: GRPCServiceDescriptor {
    return AppControl_AppControlClientMetadata.serviceDescriptor
  }

  internal var interceptors: AppControl_AppControlClientInterceptorFactoryProtocol? {
    return nil
  }

  internal func makeChangeMicrophoneStatusCall(
    _ request: AppControl_ChangeMicrophoneStatusRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<AppControl_ChangeMicrophoneStatusRequest, SwiftProtobuf.Google_Protobuf_Empty> {
    return self.makeAsyncUnaryCall(
      path: AppControl_AppControlClientMetadata.Methods.changeMicrophoneStatus.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeChangeMicrophoneStatusInterceptors() ?? []
    )
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension AppControl_AppControlAsyncClientProtocol {
  internal func changeMicrophoneStatus(
    _ request: AppControl_ChangeMicrophoneStatusRequest,
    callOptions: CallOptions? = nil
  ) async throws -> SwiftProtobuf.Google_Protobuf_Empty {
    return try await self.performAsyncUnaryCall(
      path: AppControl_AppControlClientMetadata.Methods.changeMicrophoneStatus.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeChangeMicrophoneStatusInterceptors() ?? []
    )
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
internal struct AppControl_AppControlAsyncClient: AppControl_AppControlAsyncClientProtocol {
  internal var channel: GRPCChannel
  internal var defaultCallOptions: CallOptions
  internal var interceptors: AppControl_AppControlClientInterceptorFactoryProtocol?

  internal init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: AppControl_AppControlClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

#endif // compiler(>=5.6)

internal protocol AppControl_AppControlClientInterceptorFactoryProtocol: GRPCSendable {

  /// - Returns: Interceptors to use when invoking 'changeMicrophoneStatus'.
  func makeChangeMicrophoneStatusInterceptors() -> [ClientInterceptor<AppControl_ChangeMicrophoneStatusRequest, SwiftProtobuf.Google_Protobuf_Empty>]
}

internal enum AppControl_AppControlClientMetadata {
  internal static let serviceDescriptor = GRPCServiceDescriptor(
    name: "AppControl",
    fullName: "app_control.AppControl",
    methods: [
      AppControl_AppControlClientMetadata.Methods.changeMicrophoneStatus,
    ]
  )

  internal enum Methods {
    internal static let changeMicrophoneStatus = GRPCMethodDescriptor(
      name: "ChangeMicrophoneStatus",
      path: "/app_control.AppControl/ChangeMicrophoneStatus",
      type: GRPCCallType.unary
    )
  }
}

/// To build a server, implement a class that conforms to this protocol.
internal protocol AppControl_AppControlProvider: CallHandlerProvider {
  var interceptors: AppControl_AppControlServerInterceptorFactoryProtocol? { get }

  func changeMicrophoneStatus(request: AppControl_ChangeMicrophoneStatusRequest, context: StatusOnlyCallContext) -> EventLoopFuture<SwiftProtobuf.Google_Protobuf_Empty>
}

extension AppControl_AppControlProvider {
  internal var serviceName: Substring {
    return AppControl_AppControlServerMetadata.serviceDescriptor.fullName[...]
  }

  /// Determines, calls and returns the appropriate request handler, depending on the request's method.
  /// Returns nil for methods not handled by this service.
  internal func handle(
    method name: Substring,
    context: CallHandlerContext
  ) -> GRPCServerHandlerProtocol? {
    switch name {
    case "ChangeMicrophoneStatus":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<AppControl_ChangeMicrophoneStatusRequest>(),
        responseSerializer: ProtobufSerializer<SwiftProtobuf.Google_Protobuf_Empty>(),
        interceptors: self.interceptors?.makeChangeMicrophoneStatusInterceptors() ?? [],
        userFunction: self.changeMicrophoneStatus(request:context:)
      )

    default:
      return nil
    }
  }
}

#if compiler(>=5.6)

/// To implement a server, implement an object which conforms to this protocol.
@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
internal protocol AppControl_AppControlAsyncProvider: CallHandlerProvider {
  static var serviceDescriptor: GRPCServiceDescriptor { get }
  var interceptors: AppControl_AppControlServerInterceptorFactoryProtocol? { get }

  @Sendable func changeMicrophoneStatus(
    request: AppControl_ChangeMicrophoneStatusRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> SwiftProtobuf.Google_Protobuf_Empty
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension AppControl_AppControlAsyncProvider {
  internal static var serviceDescriptor: GRPCServiceDescriptor {
    return AppControl_AppControlServerMetadata.serviceDescriptor
  }

  internal var serviceName: Substring {
    return AppControl_AppControlServerMetadata.serviceDescriptor.fullName[...]
  }

  internal var interceptors: AppControl_AppControlServerInterceptorFactoryProtocol? {
    return nil
  }

  internal func handle(
    method name: Substring,
    context: CallHandlerContext
  ) -> GRPCServerHandlerProtocol? {
    switch name {
    case "ChangeMicrophoneStatus":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<AppControl_ChangeMicrophoneStatusRequest>(),
        responseSerializer: ProtobufSerializer<SwiftProtobuf.Google_Protobuf_Empty>(),
        interceptors: self.interceptors?.makeChangeMicrophoneStatusInterceptors() ?? [],
        wrapping: self.changeMicrophoneStatus(request:context:)
      )

    default:
      return nil
    }
  }
}

#endif // compiler(>=5.6)

internal protocol AppControl_AppControlServerInterceptorFactoryProtocol {

  /// - Returns: Interceptors to use when handling 'changeMicrophoneStatus'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeChangeMicrophoneStatusInterceptors() -> [ServerInterceptor<AppControl_ChangeMicrophoneStatusRequest, SwiftProtobuf.Google_Protobuf_Empty>]
}

internal enum AppControl_AppControlServerMetadata {
  internal static let serviceDescriptor = GRPCServiceDescriptor(
    name: "AppControl",
    fullName: "app_control.AppControl",
    methods: [
      AppControl_AppControlServerMetadata.Methods.changeMicrophoneStatus,
    ]
  )

  internal enum Methods {
    internal static let changeMicrophoneStatus = GRPCMethodDescriptor(
      name: "ChangeMicrophoneStatus",
      path: "/app_control.AppControl/ChangeMicrophoneStatus",
      type: GRPCCallType.unary
    )
  }
}
